import {escapeHtml as esc,dateLabel,safeSource,termLabel,unknownLabels,observationStatus,referenceDisplay} from './business-labels.js';
export function verifyReferences(data,snapshotRunId){if(data?.schemaVersion!=='earn-public-reference/1.0'||data.scope!=='external-public-only'||data.boundSnapshotRunId!==snapshotRunId||!Array.isArray(data.records)||data.currentQuoteVerified!==false)throw Error('REFERENCE_VERSION_MISMATCH');if(data.records.some(r=>r.classification!=='research-reference-only'||r.currentQuoteVerified!==false||!Array.isArray(r.acquisition)))throw Error('REFERENCE_CLASSIFICATION_INVALID');return data;}
export const referenceState=observationStatus;
export const directoryFilters={platform:'',coin:''};
export function renderReferences(root,data){root.querySelector('[data-research-references]')?.remove();const section=document.createElement('section');section.dataset.researchReferences='';section.className='business-panel compact-panel reference-dashboard';if(!data){section.innerHTML='<h2>目录与历史条款</h2><p>资料未读取，产品与收益未知。</p>';root.append(section);return;}
const select=(key,label,values)=>`<label>${label}<select data-directory-filter="${key}"><option value="">全部</option>${values.map(v=>`<option value="${esc(v)}" ${directoryFilters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
const rows=data.records.filter(r=>(!directoryFilters.platform||r.platform===directoryFilters.platform)&&(!directoryFilters.coin||r.coin===directoryFilters.coin)).sort((a,b)=>(Date.parse(b.observedAt)||0)-(Date.parse(a.observedAt)||0));const groups=[...new Set(rows.map(r=>r.platform))];
section.innerHTML=`<h2>目录与历史条款 <small>${rows.length}/${data.records.length}条</small></h2><p class="business-note">低优先级参考：当时页面数值，未核为当前挂牌，不与上方报价或不同风险产品直接比较。</p><div class="business-filters">${select('platform','平台',[...new Set(data.records.map(r=>r.platform))])}${select('coin','币种',[...new Set(data.records.map(r=>r.coin))])}<button type="button" data-directory-clear>清除筛选</button></div>${groups.map(platform=>`<div class="directory-group"><h3>${esc(platform)}</h3><p class="directory-common-unknown business-note">共同待核：${esc([...new Set(data.records.filter(r=>r.platform===platform).flatMap(r=>unknownLabels(r.fieldsUnknown)))].join('、'))}。</p><div class="compact-table directory-table"><div class="compact-table-head"><span>币种／目录分类</span><span>展示值／期限</span><span>实际观察／资料取得</span><span>独有异常／来源</span></div>${rows.filter(r=>r.platform===platform).map(r=>{const display=referenceDisplay(r),unique=[display.condition,/Max/.test(r.rawDisplay??'')?'页面上限，非全额收益':null,/rwa/i.test(r.title??'')?'RWA标签，资产／产品身份未核':null,r.coin==='BABY'&&/Locked/.test(r.term??'')?'锁定分类为父目录推断':null].filter(Boolean);return `<article class="compact-table-row" data-reference-row><div class="row-identity"><strong>${esc(r.coin??'币种未披露')}</strong><small>${esc(display.family)}</small></div><div><strong>${esc(display.value)}</strong><small class="status-text">${esc(termLabel(r.term))} · ${esc(display.kind)}</small></div><div class="row-dates"><small>实际观察 ${esc(dateLabel(r.observedAt))}</small>${r.observedAt!==(r.retrievedAt??r.fetchedAt)?`<small>资料取得 ${esc(dateLabel(r.retrievedAt??r.fetchedAt))}</small>`:''}<small>${esc(observationStatus(r))}</small>${r.validUntil?`<small>公告截止 ${esc(dateLabel(r.validUntil))}</small>`:''}</div><div class="row-condition">${unique.map(v=>`<small>${esc(v)}</small>`).join('')}${safeSource(r.sourceUrl,'原始目录')}</div></article>`;}).join('')}</div></div>`).join('')}`;
root.append(section);section.querySelectorAll('[data-directory-filter]').forEach(input=>input.addEventListener('change',()=>{directoryFilters[input.dataset.directoryFilter]=input.value;renderReferences(root,data);}));section.querySelector('[data-directory-clear]').addEventListener('click',()=>{directoryFilters.platform='';directoryFilters.coin='';renderReferences(root,data);});}
