import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash,webcrypto}from'node:crypto';import {readFile}from'node:fs/promises';import {loadPublicBranch}from'../src/domain/delivery.js';
globalThis.crypto??=webcrypto;
const cache=()=>{const m=new Map();return{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)}};
const owner='xxcryptoofficial-collab',repo='earn-ops-radar',branch='earn-public-data',sha='a'.repeat(40);
const releaseId='rel-test',runId='run-test';const entries={'releases/rel-test/earn-snapshot.json':JSON.stringify({meta:{scope:'external-public-only',releaseId,runId,generatedAt:'2026-10-01T01:10:00Z'}}),'releases/rel-test/run-status.json':JSON.stringify({releaseId,snapshotRunId:runId})};entries['current.json']=JSON.stringify({releaseId,snapshotRunId:runId,expectedNextAt:'2026-10-02T01:10:00Z',files:Object.fromEntries(['snapshot','status'].map((r,i)=>{const path=Object.keys(entries)[i];return[r,{path,sha256:createHash('sha256').update(entries[path]).digest('hex')}]}))});
async function fetcher(url){const u=new URL(url);if(u.hostname==='api.github.com')return Response.json({ref:`refs/heads/${branch}`,object:{type:'commit',sha}});assert.ok(u.pathname.startsWith(`/${owner}/${repo}/${sha}/`));const path=u.pathname.split('/').slice(4).join('/');return entries[path]?new Response(entries[path]):new Response('',{status:404})}
test('branch pin persists a dated cold-start fallback and ages it',async()=>{const c=cache();const initial=await loadPublicBranch(owner,repo,branch,fetcher,null,Date.parse('2026-10-01T04:00:00Z'),{cache:c});assert.equal(initial.meta.deliveryCommit,sha);const cold=await loadPublicBranch(owner,repo,branch,()=>Promise.reject(Error('offline')),null,Date.parse('2026-10-03T04:00:00Z'),{cache:c});assert.equal(cold.meta.runId,initial.meta.runId);assert.equal(cold.meta.generatedAt,initial.meta.generatedAt);assert.equal(cold.meta.cachedFallback,true);assert.equal(cold.meta.missedOrStale,true)});
test('mixed immutable bytes refuse fresh render, retaining same dated prior',async()=>{const c=cache();const a=await loadPublicBranch(owner,repo,branch,fetcher,null,Date.now(),{cache:c});const bad=async u=>String(u).includes('earn-snapshot.json')?new Response('{}'):fetcher(u);const b=await loadPublicBranch(owner,repo,branch,bad,null,Date.now(),{cache:c});assert.equal(b.meta.deliveryMismatch,true);assert.equal(b.meta.runId,a.meta.runId)});
test('corrupt cold cache cannot pass',async()=>{const c=cache();c.setItem(`earn-public-last-good:${owner}/${repo}/${branch}/`,JSON.stringify({schemaVersion:'earn-public-cache/1.0',body:'{}',sha256:'bad'}));await assert.rejects(loadPublicBranch(owner,repo,branch,()=>Promise.reject(Error('offline')),null,Date.now(),{cache:c}))});
