import {formatPercent,sortByLatestUpdate,buildSpreadAlerts} from '../domain/derive.js';
import {groupProducts,filterProducts} from '../domain/products.js';
import {visibleSnapshot,isCurrent} from '../domain/visibility.js';
import {escapeHtml as esc,dateLabel,safeSource as source} from '../domain/business-labels.js';
export const viewFilters={platform:'',coin:'',term:''};
const panel=(title,subtitle,body)=>`<section class="business-panel"><header class="business-section-head"><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></header>${body}</section>`;
const empty=s=>`<p class="business-empty">${esc(s)}</p>`;
const time=(a,f)=>`<dl><dt>数据日期</dt><dd>${esc(dateLabel(a))}</dd><dt>本轮读取</dt><dd>${esc(dateLabel(f))}</dd></dl>`;
const sectorLabel=s=>({CEX:'交易所',DEX:'链上协议',DeFi:'链上协议',Web2:'银行与传统金融'})[s]??'类别未确认';
function researchCard(r){return `<article class="business-card"><div class="card-heading"><h3>${esc(r.platform)}</h3><span class="status-pill">${esc(sectorLabel(r.sector))}</span></div><h4>${esc(r.title)}</h4><p>${esc(r.fact||r.summary)}</p>${r.conditions?`<p class="business-note">适用条件：${esc(r.conditions)}</p>`:''}${r.soWhat?`<p>通用分析：${esc(r.soWhat)}</p>`:''}${r.studyPeriod?`<p>研究期：${esc(r.studyPeriod)}</p>`:''}${r.startsAt?`<p>规则窗口：${esc(dateLabel(r.startsAt))} — ${esc(dateLabel(r.validUntil))}</p>`:''}<dl><dt>公告日期</dt><dd>${esc(dateLabel(r.publishedAt))}</dd><dt>最近核验</dt><dd>${esc(dateLabel(r.fetchedAt))}</dd></dl>${source(r.sourceUrl)}</article>`;}
const platforms=[['Binance','https://www.binance.com/en/earn'],['OKX','https://www.okx.com/earn'],['Bybit','https://www.bybit.com/en/earn/'],['Bitget','https://www.bitget.com/finance'],['Gate','https://www.gate.com/earn'],['HTX','https://www.htx.com/en-us/financial/'],['KuCoin','https://www.kucoin.com/earn']];
function coverage(raw,s){return panel('平台覆盖','已取得报价、目录观察和访问限制分开显示。',`<div class="coverage-grid">${platforms.map(([name,url])=>{const live=s.competitorApy.filter(r=>r.platform===name);const old=raw.competitorApy.filter(r=>r.platform===name);const refs=raw.researchReferences?.records?.filter(r=>r.platform===name)??[];const restricted=raw.researchReferences?.sources?.some(r=>r.id.startsWith(name.toLowerCase())&&r.status==='restricted_no_retry');const state=live.length?'有当期报价':restricted?'地区限制':old.length?'报价已陈旧':refs.length?'仅有目录参考':'暂无核实报价';const observed=[...old,...refs].map(r=>r.observedAt??r.fetchedAt).filter(Boolean).sort().at(-1);return `<article class="coverage-tile"><strong>${name}</strong><span class="status-pill ${!live.length?'warn':''}">${state}</span><p>${live.length?`${groupProducts(live).length}款产品，${live.length}条额度报价`:restricted?'未取得产品数据':old.length?'历史数值见下方，不作为现价':refs.length?'具体产品与参与条件待核':'覆盖未知，不表示平台没有产品'}</p><small>最近观察 ${esc(dateLabel(observed))}</small>${source(url,'平台入口')}</article>`;}).join('')}</div>`);}
function productCard(p,current){return `<article class="business-card quote-card ${current?'':'historical-card'}"><div class="card-heading"><h4>${esc(p.coin)} <small>${esc(p.term)}</small></h4><span class="status-pill ${current?'':'warn'}">${current?'当期公开报价':'历史报价 · 待复核'}</span></div><div class="tier-rows">${p.tiers.map(t=>`<div class="tier-row"><strong>${formatPercent(t.apy)} <small>${t.rateType==='APY'?'年化含复利（APY）':'年化不含复利（APR）'}</small></strong><span>金额 ${esc(t.tier??'未披露')}</span></div>`).join('')}</div><p class="business-note">基础与额外奖励未单列；参与资格、剩余额度以产品页为准。</p>${p.eligibility?`<p>资格：${esc(p.eligibility)}</p>`:''}${p.validUntil?`<p>规则截止：${esc(dateLabel(p.validUntil))}</p>`:''}${time(p.dataAsOf,p.fetchedAt)}<p class="business-note">${p.dataTimeKind==='response'?'数据日期为公开响应时间；平台未披露产品独立利率更新时间。':p.dataTimeKind==='observed'?'数据日期为页面观察时间；平台未披露产品独立利率更新时间。':'利率口径以原始产品来源为准。'}${current?'':' 此后未取得可信新值。'}</p>${source(p.sourceUrl,'报价来源')}</article>`;}
function quotes(raw,s){const current=s.competitorApy;const old=raw.competitorApy.filter(r=>!current.includes(r)&&!isCurrent(r));const select=(key,label,values)=>`<label>${label}<select data-filter="${key}"><option value="">全部</option>${values.map(v=>`<option value="${esc(v)}" ${viewFilters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;const filters=`<div class="business-filters">${select('platform','平台',[...new Set(raw.competitorApy.map(r=>r.platform))])}${select('coin','币种',[...new Set(raw.competitorApy.map(r=>r.coin))])}${select('term','期限',['活期','定期'])}<button type="button" data-clear>清除筛选</button></div>`;const group=(rows,live)=>{const products=groupProducts(filterProducts(rows,viewFilters));return platforms.map(([name])=>{const matches=products.filter(r=>r.platform===name);return matches.length?`<h3 class="business-group-title">${name} · ${matches.length}款</h3><div class="business-grid">${matches.map(r=>productCard(r,live)).join('')}</div>`:'';}).join('')||empty(live?'当前筛选下暂无可信当期报价':'当前筛选下无历史报价');};return panel('交易所产品报价','APR、APY、金额阶梯和期限分别保留；不同条件不直接比较。',filters+group(current,true)+(old.length?`<h3 class="business-group-title">历史报价</h3><p class="business-note">以下保留最后真实观察日；不作为当前可购利率。</p>${group(old,false)}`:''));}
const coverageLabels={ 'aave-stable':'以太坊 USDT／USDC 借贷池，取各池历史最近点。','sol-staking-proxy':'JitoSOL质押代理收益，不是SOL理财挂牌。','susde':'合成美元质押参考；最近可用来源及退出条件以原始页面为准。','funding-mean':'永续合约资金费率年化，不是理财产品收益。','treasury-3m':'美国3个月国债市场收益率；官方仅披露业务日期。','eth-staking':'未取得可信公开观察。','lido-steth':'stETH质押浮动收益，不等于固定收益或即时赎回报价。','ally-savings':'美国储蓄账户，浮动APY；开户及地区资格以银行条款为准。'};
function yieldCard(r){const current=isCurrent(r);return `<article class="business-card ${current?'':'historical-card'}"><div class="card-heading"><h4>${esc(r.name)}</h4><span class="status-pill ${current?'':'warn'}">${current?'近期来源值':r.dataAsOf?'历史参考 · 待复核':'数据未取得'}</span></div><div class="business-value">${Number.isFinite(r.value)&&r.dataAsOf?formatPercent(r.value):'—'}<small>${/% APY/.test(r.unit??'')?'年化含复利（APY）':/% APR/.test(r.unit??'')?'年化不含复利（APR）':'年化参考'}</small></div><p class="business-note">${esc(coverageLabels[r.id]??'口径与参与条件以来源页面为准。')}</p>${time(r.dataAsOf,r.fetchedAt)}${source(r.sourceUrl,'原始收益来源')}</article>`;}
function yields(raw){const chain=[...(raw.externalYields??[]).filter(r=>r.sector==='DEX'),...raw.upstream.filter(r=>['aave-stable','sol-staking-proxy','susde','eth-staking'].includes(r.id))];const traditional=[...(raw.externalYields??[]).filter(r=>r.sector==='Web2'),...raw.upstream.filter(r=>r.id==='treasury-3m')];const market=raw.upstream.filter(r=>r.id==='funding-mean');return panel('外部收益与市场参考','链上协议、银行产品、国债及资金费率分组展示，不形成统一收益排名。',`<h3>链上协议</h3><div class="business-grid">${chain.map(yieldCard).join('')}</div><h3>银行与国债</h3><div class="business-grid">${traditional.map(yieldCard).join('')}</div><h3>市场基准</h3><div class="business-grid">${market.map(yieldCard).join('')}</div>`);}
export function renderApp(root,raw){const s=visibleSnapshot(raw);const records=s.competitorActions;const actions=records.filter(r=>!['mechanism','distribution','regional'].includes(r.contentKind));const references=records.filter(r=>['mechanism','distribution','regional'].includes(r.contentKind));const alerts=buildSpreadAlerts(s).filter(r=>r.evidenceKind!=='demo');const status=raw.meta.latestAttempt?.status??raw.meta.runStatus;root.innerHTML=`<main class="business-dashboard"><header class="business-masthead"><h1>赚币观察看板</h1><p>最近采集 ${esc(dateLabel(raw.meta.latestAttempt?.finishedAt??raw.meta.generatedAt))} · ${status==='COMMITTED'?'公开来源已更新':status==='FAILED'?'本轮读取失败，保留上次记录':'部分来源缺失'}</p></header>${coverage(raw,s)}${panel('活动与产品变化','正式规则、条件与核验日期直接展开。',actions.length?`<div class="business-grid">${sortByLatestUpdate(actions,['fetchedAt']).map(researchCard).join('')}</div>`:empty('当前没有满足时效条件的新活动或产品变化'))}${alerts.length?panel('利率变化','仅列有真实前后观察的变动。',`<div class="business-grid">${alerts.map(r=>`<article class="business-card"><h3>${esc(r.title)}</h3><p>${esc(r.whatChanged)}</p>${time(r.dataAsOf,r.fetchedAt)}${source(r.sourceUrl)}</article>`).join('')}</div>`):''}${quotes(raw,s)}${yields(raw)}${references.length?panel('机制、渠道与地区研究','样本、研究期及适用条件见各条记录。',`<div class="business-grid">${references.map(researchCard).join('')}</div>`):''}<footer class="business-note">时间均为北京时间。历史报价保留原日期；目录观察、市场基准和产品报价分别阅读。</footer></main>`;}
