import copy from './workbench-copy.js';
import {researchWorkbench} from './workbench.js';
import {groupProducts,filterProducts} from '../domain/products.js';
import {visibleSnapshot,isCurrent,publicNews} from '../domain/visibility.js';
import {escapeHtml as esc,dateLabel,safeSource,comparisonWindow} from '../domain/business-labels.js';
import {buildSpreadAlerts} from '../domain/derive.js';
export const viewFilters={platform:'',coin:'',term:''};
const percent=v=>Number.isFinite(v)?`${v}%`:'未取得';
const marketPercent=v=>Number.isFinite(v)?`${v.toFixed(2)}%`:'未取得';
const coins=['USDT','USDC','BTC','ETH','SOL'];
const stable=(a,b)=>a.platform.localeCompare(b.platform)||(coins.indexOf(a.coin)-coins.indexOf(b.coin))||String(a.productId).localeCompare(String(b.productId),undefined,{numeric:true})||a.term.localeCompare(b.term);
const section=(title,body,id='')=>`<section class="reference-section" ${id?`id="${id}"`:''}><h2>${esc(title)}</h2>${body}</section>`;
function filters(raw){const select=(key,label,values)=>`<label>${esc(label)}<select data-filter="${key}"><option value="">全部</option>${values.map(v=>`<option value="${esc(v)}" ${viewFilters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;const terms=[...new Set(raw.map(r=>r.term==='活期'?'活期':/^定期/.test(r.term??'')?'定期':null).filter(Boolean))];return `<div class="lookup-filters">${select('platform',copy.quotes.platform,[...new Set(raw.map(r=>r.platform))])}${select('coin',copy.quotes.coin,[...new Set(raw.map(r=>r.coin))])}${select('term',copy.quotes.term,terms)}<button data-clear type="button">${esc(copy.quotes.clear)}</button></div>`;}
function quoteTable(rows,historical){const products=groupProducts(filterProducts(rows,viewFilters)).sort(stable);if(!products.length)return `<p class="empty-result">${esc(copy.quotes.empty)} <button type="button" data-clear>${esc(copy.quotes.clear)}</button></p>`;
 return `<p class="batch-note">${[...new Set(products.map(p=>p.note).filter(Boolean))].map(esc).join(' · ')}</p><div class="data-table quote-table"><div class="table-heading"><span>平台 / 产品身份 / 币种 / 期限</span><span>金额阶梯 · APR/APY</span><span>真实数据 / 采集时间</span><span>条件与来源</span></div>${products.map(p=>`<article class="table-row quote-row ${historical?'historical':''}" data-quote-product data-product-id="${esc(p.productId)}" data-product-key="${esc(p.key)}"><div class="product-identity"><strong>${esc(p.platform)} · ${esc(p.coin)}</strong><span>${esc(p.term)} · 产品 ${esc(p.productId)}</span></div><div class="rate-tiers">${p.tiers.map(t=>`<div data-quote-tier data-tier-key="${esc(JSON.stringify([t.platform,t.productId,t.coin,t.term,t.tier,t.rateType,t.dataAsOf,t.fetchedAt]))}"><strong>${percent(t.apy)} <small>${esc(t.rateType)}</small></strong><span>${esc(t.tier??'金额未披露')}</span></div>`).join('')}</div><div class="record-time"><span>数据 ${esc(dateLabel(p.dataAsOf))}</span><span>采集 ${esc(dateLabel(p.fetchedAt))}</span>${historical?'<em>历史 · 待复核</em>':''}</div><div class="record-source">${p.eligibility?`<span>${esc(p.eligibility)}</span>`:''}${p.validUntil?`<span>截止 ${esc(dateLabel(p.validUntil))}</span>`:''}<span>${p.dataTimeKind==='observed'?'页面观察':p.dataTimeKind==='date-only'?'来源仅披露日期':'来源响应时间'}；独立利率更新时间未披露</span>${safeSource(p.sourceUrl,copy.quotes.source)}</div></article>`).join('')}</div>`;}
function quotes(raw,now){const valid=(raw.competitorApy??[]).filter(r=>! /coinw|币赢/i.test(r.platform??''));const current=visibleSnapshot(raw,now).competitorApy,history=valid.filter(r=>!current.includes(r));const platforms=[...new Set(current.map(r=>r.platform))];return `<section id="quotes" class="quote-shelf"><h2>${esc(copy.quotes.title)}</h2><p class="section-note">${esc(platforms.length===1&&platforms[0]==='Bitget'?copy.quotes.noteSingle:copy.quotes.noteMultiple)}</p>${filters(valid)}<h3>${esc(copy.quotes.recent)}</h3>${quoteTable(current,false)}<h3>${esc(copy.quotes.history)}</h3>${quoteTable(history,true)}<p class="section-note">${esc(copy.quotes.conditionNote)}</p></section>`;}
function market(snapshot,now){const rows=[...(snapshot.externalYields??[]),...(snapshot.upstream??[])],groups=[['protocol',rows.filter(r=>!['ally-savings','treasury-3m','funding-mean'].includes(r.id))],['bank',rows.filter(r=>['ally-savings','treasury-3m'].includes(r.id))],['funding',rows.filter(r=>r.id==='funding-mean')]];const changes=buildSpreadAlerts(visibleSnapshot(snapshot,now)).filter(a=>a.id?.startsWith('upstream-'));
 return section(copy.reference.marketTitle,groups.map(([kind,items])=>`<div class="market-group"><h3>${esc(copy.reference[kind])}</h3>${items.map(r=>{const change=changes.find(a=>a.id==='upstream-'+r.id),window=change?comparisonWindow(change,snapshot):null;return `<article class="market-row"><div><strong>${esc(r.name)}</strong><span>${esc(r.unit??'口径未知')}</span></div><div><strong data-source-value="${esc(r.value??'')}">${marketPercent(r.dataAsOf?r.value:null)}</strong><span>${isCurrent(r,now)?'最近来源值':r.dataAsOf?'历史参考 · 待复核':'数据未取得'}</span></div><div><span>数据 ${esc(dateLabel(r.dataAsOf))}</span><span>采集 ${esc(dateLabel(r.fetchedAt))}</span>${window?.confirmed?`<span class="comparison-window">${esc(window.label)} · ${change.changeBp>0?'↑':'↓'}${Math.abs(change.changeBp).toFixed(0)}基点</span>`:''}</div>${safeSource(r.sourceUrl,'原始来源')}</article>`;}).join('')}</div>`).join(''));}
function health(s){const names={'bybit-funding':'Bybit资金费率','binance-funding':'Binance资金费率','bybit-earn':'Bybit理财'},impact={'bybit-funding':'不能更新Bybit资金费率参考','binance-funding':'不能更新Binance资金费率参考','bybit-earn':'不能判断Bybit当前挂牌或跨平台价格'};const runs=s.sourceRuns??[],failed=runs.filter(r=>r.status==='failed');return section(copy.reference.healthTitle,`<p class="section-note">${esc(copy.reference.healthNote)}</p><p class="health-summary">${runs.filter(r=>r.status==='fresh').length}个来源读回 / ${failed.length}个来源失败</p>${failed.map(r=>`<div class="source-state"><strong>${esc(names[r.id]??r.id)}</strong><span>${esc(impact[r.id]??'依赖此来源的结论待核')}</span><time>${esc(dateLabel(r.fetchedAt))}</time></div>`).join('')}<p class="version-note">最后可信公开数据 ${esc(dateLabel(s.meta.generatedAt))} 北京时间 · ${esc(s.meta.runStatus)}${s.meta.deliveryMismatch?' · 本次读取绑定失败，保留旧版':s.meta.missedOrStale?' · 已超过预期更新窗口':''}</p>`);}
function otherResearch(s,now){const items=visibleSnapshot(s,now).competitorActions;if(!items.length)return '';return section('其他公开规则观察',items.map(r=>`<article class="other-rule"><strong>${esc(r.platform)} · ${esc(r.title)}</strong><p>${esc(r.fact||r.summary)}</p><p>${esc(r.conditions??'')}</p>${safeSource(r.sourceUrl)}<span>核验 ${esc(dateLabel(r.fetchedAt))}</span></article>`).join(''));}
export function renderApp(root,raw,now=Date.now()){if(!raw){root.innerHTML=`<main class="earn-workbench">${researchWorkbench(null,now)}<p class="load-state">${esc(copy.loading)}</p></main>`;return;}root.innerHTML=`<main class="earn-workbench">${researchWorkbench(raw,now)}${otherResearch(raw,now)}${quotes(raw,now)}<section id="reference" class="global-reference"><h2>${esc(copy.reference.title)}</h2><div data-directory-host></div>${market(raw,now)}${health(raw)}</section></main>`;}
