import {formatPercent,sortByLatestUpdate,buildSpreadAlerts} from '../domain/derive.js';
import {groupProducts,filterProducts} from '../domain/products.js';
import {visibleSnapshot,isCurrent} from '../domain/visibility.js';
import {escapeHtml as esc,dateLabel,safeSource as source,comparisonWindow} from '../domain/business-labels.js';
export const viewFilters={platform:'',coin:'',term:''};
const panel=(title,note,body)=>`<section class="business-panel compact-panel"><header><h2>${esc(title)}</h2>${note?`<p class="business-note">${esc(note)}</p>`:''}</header>${body}</section>`;
const empty=s=>`<p class="compact-empty">${esc(s)}</p>`;
const platforms=[['Binance','https://www.binance.com/en/earn'],['OKX','https://www.okx.com/earn'],['Bybit','https://www.bybit.com/en/earn/'],['Bitget','https://www.bitget.com/finance'],['Gate','https://www.gate.com/earn'],['HTX','https://www.htx.com/en-us/financial/'],['KuCoin','https://www.kucoin.com/earn']];
function filters(raw){const select=(key,label,values)=>`<label>${label}<select data-filter="${key}"><option value="">全部</option>${values.map(v=>`<option value="${esc(v)}" ${viewFilters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;return `<div class="business-filters">${select('platform','平台',[...new Set(raw.competitorApy.map(r=>r.platform))])}${select('coin','币种',[...new Set(raw.competitorApy.map(r=>r.coin))])}${select('term','期限',['活期','定期'])}<button data-clear type="button">清除筛选</button></div>`;}
function quoteTable(rows,recent){const products=groupProducts(filterProducts(rows,viewFilters));if(!products.length)return empty(recent?'暂无符合筛选条件的最近采集报价':'暂无符合筛选条件的历史报价');return `<div class="compact-table quote-table"><div class="compact-table-head"><span>平台／币种／期限</span><span>金额阶梯与年化</span><span>日期与时效</span><span>独有条件／来源</span></div>${products.map(p=>`<article class="compact-table-row" data-quote-product><div class="row-identity"><strong>${esc(p.platform)} · ${esc(p.coin)}</strong><small>${esc(p.term)}</small></div><div class="compact-tiers">${p.tiers.map(t=>`<div><strong>${formatPercent(t.apy)} <small>${esc(t.rateType)}</small></strong><span>${esc(t.tier??'金额未披露')}</span></div>`).join('')}</div><div class="row-dates"><span class="cell-label">日期与时效</span><small>采集 ${esc(dateLabel(p.fetchedAt))}</small><small>数据 ${esc(dateLabel(p.dataAsOf))}</small><span class="status-pill ${recent?'':'warn'}">${recent?'最近采集 · 36小时内':'历史报价 · 待复核'}</span></div><div class="row-condition">${p.eligibility?`<small>${esc(p.eligibility)}</small>`:''}${p.validUntil?`<small>截止 ${esc(dateLabel(p.validUntil))}</small>`:''}${source(p.sourceUrl,'报价来源')}</div></article>`).join('')}</div>`;}
function quotes(raw,s){const current=s.competitorApy,old=raw.competitorApy.filter(r=>!current.includes(r)&&!isCurrent(r));return {recent:panel('最近采集报价','APR为不含复利年化，APY含复利；基础／奖励未单列，资格及剩余额度以来源为准。数据日期为来源响应／页面观察，产品独立利率更新时间未披露。',filters(raw)+quoteTable(current,true)),history:old.length?panel('历史报价','最后可信值与原日期；不作为当前可购利率。',quoteTable(old,false)):''};}
const meanings={'aave-stable':'以太坊USDT／USDC借贷池','sol-staking-proxy':'JitoSOL质押代理，非SOL理财挂牌','susde':'合成美元质押参考，退出条件以原文为准','funding-mean':'永续资金费率年化，非理财收益','treasury-3m':'3个月国债市场收益率，只有业务日期','eth-staking':'未取得可信公开观察','lido-steth':'stETH浮动质押收益，非固定回报','ally-savings':'美国储蓄账户，开户／地区条件适用'};
function yields(raw){const rows=[...(raw.externalYields??[]),...raw.upstream].sort((a,b)=>Number(isCurrent(b))-Number(isCurrent(a)));return panel('收益与市场基准','协议收益、银行产品和市场基准分开阅读；不形成收益推荐或跨风险排名。',`<div class="compact-table yield-table"><div class="compact-table-head"><span>对象／口径</span><span>最近来源数值</span><span>数据与采集日期</span><span>性质／来源</span></div>${rows.map(r=>`<article class="compact-table-row"><div class="row-identity"><strong>${esc(r.name)}</strong><small>${esc(r.unit??'口径未知')}</small></div><div><strong>${Number.isFinite(r.value)&&r.dataAsOf?formatPercent(r.value):'—'}</strong><small class="status-text">${isCurrent(r)?'最近来源值':r.dataAsOf?'历史参考 · 待复核':'数据未取得'}</small></div><div class="row-dates"><small>数据 ${esc(dateLabel(r.dataAsOf))}</small><small>采集 ${esc(dateLabel(r.fetchedAt))}</small></div><div class="row-condition"><small>${esc(meanings[r.id]??'条件以原始来源为准')}</small>${source(r.sourceUrl,'原始来源')}</div></article>`).join('')}</div>`);}
function changes(s){const rows=buildSpreadAlerts(s).filter(r=>r.evidenceKind!=='demo');return rows.length?panel('变化依据','真实比较窗口；未披露日内时间时不标今日或单日环比。',`<div class="change-list">${rows.map(r=>`<article><strong>${esc(r.title)} ${r.changeBp>0?'↑':'↓'} ${Math.abs(r.changeBp).toFixed(0)}基点</strong><small>${esc(comparisonWindow(r,s).label)}</small>${source(r.sourceUrl)}</article>`).join('')}</div>`):'';}
function coverage(raw,s){return panel('覆盖与缺口','平台有无可信报价与目录观察分开判断。',`<div class="coverage-strip">${platforms.map(([name,url])=>{const live=s.competitorApy.filter(r=>r.platform===name),old=raw.competitorApy.filter(r=>r.platform===name),refs=raw.researchReferences?.records?.filter(r=>r.platform===name)??[];const restricted=raw.researchReferences?.sources?.some(r=>r.id.startsWith(name.toLowerCase())&&r.status==='restricted_no_retry');const date=[...old,...refs].map(r=>r.observedAt??r.fetchedAt).filter(Boolean).sort().at(-1);return `<div><strong>${name}</strong><span>${live.length?'有最近采集报价':restricted?'目录地区受限':old.length?'只有历史报价':refs.length?'只有目录参考':'报价未知'}</span><small>${esc(dateLabel(date))}</small>${source(url,'官方入口')}</div>`;}).join('')}</div>`);}
function research(s){const rows=sortByLatestUpdate(s.competitorActions,['fetchedAt']);if(!rows.length)return '';return panel('其他已核研究','按最近核验时间排序，事实与条件直接可读。',`<div class="compact-research">${rows.map(r=>`<article><strong>${esc(r.platform)} · ${esc(r.title)}</strong><p>${esc(r.fact||r.summary)}</p>${r.conditions?`<p>${esc(r.conditions)}</p>`:''}${r.soWhat?`<p>通用分析：${esc(r.soWhat)}</p>`:''}<small>发布 ${esc(dateLabel(r.publishedAt))} · 核验 ${esc(dateLabel(r.fetchedAt))}${r.studyPeriod?' · 研究期 '+esc(r.studyPeriod):''}${r.validUntil?' · 截止 '+esc(dateLabel(r.validUntil)):''}</small>${source(r.sourceUrl)}</article>`).join('')}</div>`);}
export function renderApp(root,raw){const s=visibleSnapshot(raw);const {recent,history}=quotes(raw,s);root.innerHTML=`<main class="business-dashboard compact-dashboard-v2">${recent}<section data-rule-comparison></section>${changes(s)}${yields(raw)}${research(s)}${coverage(raw,s)}${history}<footer class="business-note">北京时间 · 保留真实观察日 · 未核数据不作当前报价</footer></main>`;}
