import copy from './workbench-copy.js';
import {generalResearchState,ruleTime} from './general-research.js';
import {escapeHtml as esc,safeSource,dateLabel} from '../domain/business-labels.js';
import {visibleSnapshot} from '../domain/visibility.js';
const note=(kind,text)=>`<div class="research-point"><span>${esc(copy.researchLabels[kind])}</span><p>${esc(text)}</p></div>`;
function evidence(r){return `<div class="mechanism-source">${safeSource(r.sourceUrl,copy.sourceLabel)}<span>${esc(copy.publicationLabel)} ${esc(r.publishedDate)} · ${esc(copy.verificationLabel)} ${esc(ruleTime(r.verifiedAt))}</span></div>`;}
export function researchWorkbench(snapshot,now=Date.now()){
 const rules=generalResearchState(now),[b,y]=rules,live=snapshot?visibleSnapshot(snapshot,now).competitorApy:[],platforms=[...new Set(live.map(r=>r.platform))];
 const summary=!snapshot?copy.loading:platforms.length===1&&platforms[0]==='Bitget'?copy.summary.withQuotes:platforms.length?copy.summary.multipleQuotes:copy.summary.withoutQuotes;
 const hasQuote=name=>live.some(r=>r.platform===name),hasHistory=name=>(snapshot?.competitorApy??[]).some(r=>r.platform===name),hasDirectory=name=>(snapshot?.researchReferences?.records??[]).some(r=>r.platform===name),restricted=name=>(snapshot?.researchReferences?.sources??[]).some(r=>r.id.startsWith(name.toLowerCase())&&r.status==='restricted_no_retry');const scope=[['Binance',hasDirectory('Binance')?'规则 / 目录':'规则'],['Bybit',hasQuote('Bybit')?'规则 / 最近报价':hasHistory('Bybit')?'规则 / 历史报价':'规则'],['Bitget',hasQuote('Bitget')?'最近报价':hasHistory('Bitget')?'历史报价待核':copy.scopeUnknown],['OKX',restricted('OKX')?'目录受限':hasDirectory('OKX')?'目录参考':copy.scopeUnknown],...['Gate','HTX','KuCoin'].map(name=>[name,hasQuote(name)?'最近报价':hasDirectory(name)?'目录参考':copy.scopeUnknown])];
 const status=b.expired?copy.binance.expired:b.verificationStale?copy.binance.stale:'';
 const yStatus=y.expired?copy.bybit.expired:y.verificationStale?copy.bybit.stale:'';
 const research=c=>`<aside class="mechanism-research">${note('hypothesis',c.hypothesis)}${note('verify',c.verify)}${note('gap',c.gap)}</aside>`;
 return `<header class="workbench-head"><div><h1>${esc(copy.title)}</h1><span class="observation-date">${snapshot?esc(dateLabel(snapshot.meta.generatedAt))+' 北京公开数据':esc(copy.loading)}</span></div><nav aria-label="页面定位"><a href="#mechanisms">${esc(copy.anchors.mechanisms)}</a><a href="#quotes">${esc(copy.anchors.quotes)}</a><a href="#reference">${esc(copy.anchors.reference)}</a></nav><p>${esc(summary)}</p>${snapshot?.meta.deliveryMismatch||snapshot?.meta.missedOrStale?`<p class="delivery-state">${esc(copy.lastGood)} ${esc(dateLabel(snapshot.meta.generatedAt))}</p>`:''}</header>
 <section id="mechanisms" class="work-surface" aria-labelledby="mechanism-title"><aside class="observation-scope"><h2>${esc(copy.scopeTitle)}</h2><ul>${scope.map(([name,state])=>`<li><strong>${esc(name)}</strong><span>${esc(state)}</span></li>`).join('')}</ul><p class="scope-note">${esc(copy.scopeNote)}</p></aside>
 <div class="mechanism-work"><div class="work-surface-head"><h2 id="mechanism-title">${esc(copy.mechanismsTitle)}</h2><span>${esc(copy.legend)}</span></div>
 <article class="mechanism-unit binance-unit ${b.expired?'window-expired':''}" data-mechanism="binance"><div class="mechanism-diagram"><h3>Binance <span>${esc(copy.binance.name)}</span></h3><div class="amount-layers" aria-label="额度与收益的规则关系"><div class="amount-label">${esc(copy.binance.amountFirst)}</div><div class="amount-label">${esc(copy.binance.amountRest)}</div><div class="bonus-layer"><strong>${esc(copy.binance.bonus)}</strong><small>${esc(copy.binance.cutoffLabel.split('：')[0])} ${esc(ruleTime(b.validUntil))}</small></div><div class="bonus-absent">${esc(copy.binance.base)}</div><div class="base-layer">${esc(copy.binance.base)}</div></div><p class="rule-caption">${esc(copy.binance.baseNote)}</p><p class="window-note">${esc(status||copy.binance.after)}</p></div>${research(copy.binance)}${evidence(b)}</article>
 <article class="mechanism-unit bybit-unit ${y.expired?'window-expired':''}" data-mechanism="bybit"><div class="mechanism-diagram"><h3>Bybit <span>${esc(copy.bybit.name)}</span></h3><p class="rule-caption">${esc(copy.bybit.qualify)}</p><div class="reward-flow" aria-label="参与余额到奖励到账的规则关系"><div><strong>USD1</strong></div><div><strong>24次 → 最低</strong><span>${esc(copy.bybit.measure)}</span><span class="flow-exclude">${esc(copy.bybit.exclude)}</span></div><div><strong>WLFI</strong></div><div><strong>次日约14:00 北京</strong><span>${esc(copy.bybit.payment.split('（')[0])}</span></div></div><p class="window-note">${esc(copy.bybit.windowLabel.split('：')[0])} ${esc(ruleTime(y.validUntil))}${yStatus?' · '+esc(yStatus):''}</p></div>${research(copy.bybit)}${evidence(y)}</article></div></section>`;
}
